### PR TITLE
add dependabot and ci

### PR DESCRIPTION
**Pull request by theavege**
<b>Hello!</b>

Thanks for your app.
I made some minor edits.
I hope they are useful.

<i>Thanks.</i>

### CODE REVIEW

**Comment by mdharm** [comment]
I am __highly__ suspicious of this pull request.  It seems to pull into the CI a repo which claims to be a C-to-fltk binding, but this project doesn't use fltk.  This pull request is also virtually identical to many others from this account.  Given that this other repo would get built/run every night for no apparent purpose, I would recommend rejecting this request.

Looking at this user's history, either this is someone who is doing a low-quality cut-and-paste job to add CI to rust projects (many of which do use fltk), or this is an attempt to get this other repo (https://github.com/MoAlyousef/cfltk) built and run on a regular basis for a nefarious purpose.  I'm told that repo looks legit, but it doesn't explain why a C-to-fltk binding repo would be needed for a project in Rust.

This may be the first step in a multi-step attempt to compromise this repo.  First, merge a harmless-looking PR that adds dependabot and a CI step that seems harmless, but runs _every night_.  Malicious components might come later.

FYI, I found this PR when a friend asked me to review a PR on his project, which seemed similarly suspicious (for slightly different reasons).

**Comment by theavege** [comment]
@mdharm For CI I took this as a [basis](https://github.com/fltk-rs/demos/blob/master/.github/workflows/rust.yml)
For "dependabot" I took this as a [basis](https://github.com/fltk-rs/fltk-rs/blob/master/.github/dependabot.yml)
I use the FLTK-rs library, [MoAlyousef](https://github.com/MoAlyousef) can confirm.
I try to help with projects using FLTK-rs, Ratatui and Yew.

What crimes do you accuse me of?
What comments do you have?

**Comment by PonasKovas** [comment]
This is very interesting...

> I try to help with projects using FLTK-rs, Ratatui and Yew.

To me it appears this specific project uses none of these...

**Comment by PonasKovas** [comment]
What happened here..? :thinking:  https://github.com/fltk-rs/demos/pull/34

**Comment by theavege** [comment]
@PonasKovas There were deleted my messages by MoAlyousef, like [that](https://github.com/fltk-rs/fltk-rs/issues/418) and [that](https://github.com/fltk-rs/flemish/pull/11).

**Comment by theavege** [comment]
@PonasKovas this specific [project](https://github.com/CM-IV/crypto_rs/tree/fltk) uses FLTK-rs.

**Comment by PonasKovas** [comment]
Oh, I didn't notice this branch. You're making the PR to the wrong branch then.

You have to admit that it's suspicious when someone starts making PRs to old and unpopular repositories with a long build script, which includes a cron job (I understand you took it from the FLTK example, and I don't blame you, it's actually very weird why they have it in there, I have no idea what is it's purpose).

Anyway, if you're actually genuine, I am truly sorry for suspecting you of malicious intent. Please don't take it personally.

Hope you have a good day

**Comment by MoAlyousef** [comment]
Hi

This user was banned from the fltk-rs org for several reasons:
- meaningless PRs
- Very large PRs
- Ignoring suggestions
- Broken code
- Copying code from other repos without attribution or permission

It seemed most his activity just led to meaningless churn for suspect reasons. 
Anyway his changes to repos under fltk-rs were reverted.

**Comment by theavege** [comment]
@MoAlyousef Anyway my changes to repos under fltk-rs, [demos](https://github.com/fltk-rs/demos) and [flemish](https://github.com/fltk-rs/flemish) were reverted. Why did you delete my messages?

**Pull request closed without merging**
